---
name: üìù Markdown Lint CI

on:
  push:
    branches: [main, 'release/*']
    tags: ['v*']
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-markdown-lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdownlint:
    name: Markdown Lint
    uses: N3b3x/hf-general-ci-tools/.github/workflows/ru-markdown-lint.yml@main
    with:
      globs: 'docs/** *.md **/*.md'
      exclude_patterns: '.git/**,node_modules/**,venv/**,.venv/**,_site/**,hf-core-drivers/**,hf-core-utils/**'
      config_file: '_config/.markdownlint.json'
      use_docker: false
      fix: false
      separator: ''
